In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import math
import seaborn as sns

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('ptRnnW.csv')

In [4]:
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3217,ohc,six,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [5]:
df.info('carlength')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [7]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [8]:
df.shape

(205, 26)

In [9]:
df.nunique()

car_ID              205
symboling             6
CarName             147
fueltype              2
aspiration            2
doornumber            2
carbody               5
drivewheel            3
enginelocation        2
wheelbase            53
carlength            75
carwidth             44
carheight            49
curbweight          171
enginetype            7
cylindernumber        7
enginesize           44
fuelsystem            8
boreratio            38
stroke               37
compressionratio     32
horsepower           59
peakrpm              23
citympg              29
highwaympg           30
price               189
dtype: int64

In [10]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
200    False
201    False
202    False
203    False
204    False
Length: 205, dtype: bool

# CAR PRICE PREDICTION

In [11]:
df.sort_values(by=['CarName','horsepower','price'], ascending=False)

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
190,191,3,vw rabbit,gas,std,two,hatchback,fwd,front,94.5,165.7,64.0,51.4,2221,ohc,four,109,mpfi,3.19,3.40,8.5,90,5500,24,29,9980.0
189,190,3,vw dasher,gas,std,two,convertible,fwd,front,94.5,159.3,64.2,55.6,2254,ohc,four,109,mpfi,3.19,3.40,8.5,90,5500,24,29,11595.0
199,200,-1,volvo diesel,gas,turbo,four,wagon,rwd,front,104.3,188.8,67.2,57.5,3157,ohc,four,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950.0
198,199,-2,volvo 264gl,gas,turbo,four,sedan,rwd,front,104.3,188.8,67.2,56.2,3045,ohc,four,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
89,90,1,Nissan versa,gas,std,two,sedan,fwd,front,94.5,165.3,63.8,54.5,1889,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,5499.0

In [12]:
!pip install word2number

Requirement already satisfied: word2number in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (1.1)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
from word2number import w2n
df['doornumber']=df['doornumber'].apply(w2n.word_to_num)
df['doornumber']

0      2
1      2
2      2
3      4
4      4
      ..
200    4
201    4
202    4
203    4
204    4
Name: doornumber, Length: 205, dtype: int64

In [14]:
df['price'].astype(int)

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: int64

In [15]:
df1=df.drop(columns=['car_ID', 'symboling', 'enginelocation', 'carlength', 'carwidth' ,'carheight', 'stroke', 'boreratio', 'wheelbase'])
df1

,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,alfa-romero giulia,gas,std,2,convertible,rwd,2548,dohc,four,130,mpfi,9.0,111,5000,21,27,13495.0
1,alfa-romero stelvio,gas,std,2,convertible,rwd,2548,dohc,four,130,mpfi,9.0,111,5000,21,27,16500.0
2,alfa-romero Quadrifoglio,gas,std,2,hatchback,rwd,2823,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500.0
3,audi 100 ls,gas,std,4,sedan,fwd,2337,ohc,four,109,mpfi,10.0,102,5500,24,30,13950.0
4,audi 100ls,gas,std,4,sedan,4wd,2824,ohc,five,136,mpfi,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo 145e (sw),gas,std,4,sedan,rwd,2952,ohc,four,141,mpfi,9.5,114,5400,23,28,16845.0
201,volvo 144ea,gas,turbo,4,sedan,rwd,3049,ohc,four,141,mpfi,8.7,160,5300,19,25,19045.0
202,volvo 244dl,gas,std,4,sedan,rwd,3012,ohcv,six,173,mpfi,8.8,134,5500,18,23,21485.0
203,volvo 246,diesel,turbo,4,sedan,rwd,3217,ohc,six,145,idi,23.0,106,4800,26,27,22470.0
204,volvo 264gl,gas,turbo,4,sedan,rwd,3062,ohc,four,141,mpfi,9.5,114,5400,19,25,22625.0

In [16]:
df1['cylindernumber']=df['cylindernumber'].apply(w2n.word_to_num)
df1['cylindernumber']

0      4
1      4
2      6
3      4
4      5
      ..
200    4
201    4
202    6
203    6
204    4
Name: cylindernumber, Length: 205, dtype: int64

In [17]:
df1

,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,alfa-romero giulia,gas,std,2,convertible,rwd,2548,dohc,4,130,mpfi,9.0,111,5000,21,27,13495.0
1,alfa-romero stelvio,gas,std,2,convertible,rwd,2548,dohc,4,130,mpfi,9.0,111,5000,21,27,16500.0
2,alfa-romero Quadrifoglio,gas,std,2,hatchback,rwd,2823,ohcv,6,152,mpfi,9.0,154,5000,19,26,16500.0
3,audi 100 ls,gas,std,4,sedan,fwd,2337,ohc,4,109,mpfi,10.0,102,5500,24,30,13950.0
4,audi 100ls,gas,std,4,sedan,4wd,2824,ohc,5,136,mpfi,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo 145e (sw),gas,std,4,sedan,rwd,2952,ohc,4,141,mpfi,9.5,114,5400,23,28,16845.0
201,volvo 144ea,gas,turbo,4,sedan,rwd,3049,ohc,4,141,mpfi,8.7,160,5300,19,25,19045.0
202,volvo 244dl,gas,std,4,sedan,rwd,3012,ohcv,6,173,mpfi,8.8,134,5500,18,23,21485.0
203,volvo 246,diesel,turbo,4,sedan,rwd,3217,ohc,6,145,idi,23.0,106,4800,26,27,22470.0
204,volvo 264gl,gas,turbo,4,sedan,rwd,3062,ohc,4,141,mpfi,9.5,114,5400,19,25,22625.0

In [18]:
df1['fueltype']=df1['fueltype'].map({'gas':0, 'diesel':1})
df1

,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,alfa-romero giulia,0,std,2,convertible,rwd,2548,dohc,4,130,mpfi,9.0,111,5000,21,27,13495.0
1,alfa-romero stelvio,0,std,2,convertible,rwd,2548,dohc,4,130,mpfi,9.0,111,5000,21,27,16500.0
2,alfa-romero Quadrifoglio,0,std,2,hatchback,rwd,2823,ohcv,6,152,mpfi,9.0,154,5000,19,26,16500.0
3,audi 100 ls,0,std,4,sedan,fwd,2337,ohc,4,109,mpfi,10.0,102,5500,24,30,13950.0
4,audi 100ls,0,std,4,sedan,4wd,2824,ohc,5,136,mpfi,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo 145e (sw),0,std,4,sedan,rwd,2952,ohc,4,141,mpfi,9.5,114,5400,23,28,16845.0
201,volvo 144ea,0,turbo,4,sedan,rwd,3049,ohc,4,141,mpfi,8.7,160,5300,19,25,19045.0
202,volvo 244dl,0,std,4,sedan,rwd,3012,ohcv,6,173,mpfi,8.8,134,5500,18,23,21485.0
203,volvo 246,1,turbo,4,sedan,rwd,3217,ohc,6,145,idi,23.0,106,4800,26,27,22470.0
204,volvo 264gl,0,turbo,4,sedan,rwd,3062,ohc,4,141,mpfi,9.5,114,5400,19,25,22625.0

In [19]:
reg = linear_model.LinearRegression()

In [20]:
reg.fit(df1.drop('price', axis = 'columns'), df1['price'])

ValueError: could not convert string to float: 'alfa-romero giulia'